### ISSUE TITLE
Design: 여행일기 페이지 UI 구현

### ISSUE THREAD

**Issue by HyunJinNo** [TripInfoWeb/solitour-mobile#1]
## ❓ 어떤 기능인가요?

- 여행일기 페이지 UI를 구현합니다.

## 📝 기능 설명

- 여행일기 목록 페이지, 여행일기 작성 페이지, 여행일기 상세 페이지 UI를 구현합니다.

## ✅ TODO

구현해야 하는 기능에 대해 체크리스트를 작성해 주세요.

- [ ] 여행일기 목록 페이지 UI 구현
- [ ] 여행일기 작성 페이지 UI 구현
- [ ] 여행일기 상세 페이지 UI 구현
